apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-hackfest
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/bentaljaard/hello-hackfest.git'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: buildah
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/ben/hello-hackfest'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./src/main/docker/Dockerfile.jvm-aarch64-runtime
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - multiarch-mvn
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: multiarch-mvn
      params:
        - name: GOALS
          value:
            - clean
            - package
            - '-DskipTests'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: multiarch-mvn
      workspaces:
        - name: maven-repo
          workspace: mvn-repo
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
    - name: mvn-repo
