apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: multiarch-mvn
spec:
  params:
    - default:
        - package
      description: The Maven goals to run
      name: GOALS
      type: array
  steps:
    - args:
        - '-Dmaven.repo.local=$(workspaces.maven-repo.path)'
        - $(inputs.params.GOALS)
      command:
        - /usr/bin/mvn
      image: 'quay.io/qiotproject/ubi-multiarch-maven:v1.0.2-java11'
      name: mvn
      resources: {}
      workingDir: /workspace/source
  workspaces:
    - name: maven-repo
    - description: The workspace consisting of maven project.
      name: source
