kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mvn-repo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi
  storageClassName: local
  volumeMode: Filesystem